# This file is part of the TAU 1501102301 - Python for Neuroscientists course, Spring 2026.
#
# Assignment 5:
# The data available in data.json is a table of participants in a questionnaire-type experiment. 
# The data is mostly fine, but upon a closer inspection you may identify a few missing\corrupt values 
# here and there. 
# Our goal is to clean the data and analyze the results. 
# Define a class that have several methods that process the given data. 

import numpy as np
import pandas as pd
import pathlib
from typing import Tuple, Union
import matplotlib
matplotlib.use('Agg') # This tells it to bypass Tkinter completely!
import matplotlib.pyplot as plt

class QuestionnaireAnalysis:
    """
    Reads and analyzes data generated by the questionnaire experiment.
    Should be able to accept strings and pathlib.Path objects.
    """

    def __init__(self, data_fname: Union[pathlib.Path, str]):
        """Initializes the class with the given data file name.

        Parameters
        ----------
        data_fname : Union[pathlib.Path, str]
            The name of the data file, either as a string or a pathlib.Path object.

        Raises
        ------
        TypeError
            If data_fname is not a string or pathlib.Path object.
        ValueError
            If the file specified by data_fname does not exist.

        Returns
        -------
        None
        """
        # 1. Check for valid input types (Passes test_wrong_input_type)
        if not isinstance(data_fname, (str, pathlib.Path)):
            raise TypeError(f"data_fname must be a string or pathlib.Path, got {type(data_fname)}")
        
        # 2. Convert to Path object (Passes test_str_input and test_valid_input)
        self.data_fname = pathlib.Path(data_fname)
        
        # 3. Check if file exists during instantiation (Passes test_missing_file)
        if not self.data_fname.exists():
            raise ValueError(f"File {self.data_fname} does not exist.")

    def read_data(self):
        """Reads the json data located in self.data_fname into memory, to
        the attribute self.data.

        Parameters
        ----------
        None

        Raises
        ------
        FileNotFoundError
            If the file specified by self.data_fname does not exist.

        Returns
        -------
        None
        """
        # Pandas natively handles Path objects; no built-in open() needed
        # (Passes test_data_attr_exists and test_data_attr_is_df)
        self.data = pd.read_json(self.data_fname)
            
    # 1. Plot the distribution of ages of the participants. 
    # The bins for the histogram should be [0, 10), [10, 20), [20, 30), ..., [90, 100]. 
    # The function should return the result.

    def show_age_distrib(self) -> Tuple[np.ndarray, np.ndarray]:
        """Calculates and plots the age distribution of the participants.

        Returns
        -------
        hist : np.ndarray
            Number of people in a given bin
        bins : np.ndarray
            Bin edges
        """
        # 1. Convert ages to numeric, forcing the string "nan" into actual np.nan
        ages = pd.to_numeric(self.data['age'], errors='coerce')
        
        # 2. Separate valid ages and count the missing ones
        valid_ages = ages.dropna()
        nan_count = ages.isna().sum()
        
        # 3. Calculate the standard histogram required for the return statement
        bins = np.arange(0, 101, 10)
        hist, bin_edges = np.histogram(valid_ages, bins=bins)
        
        # 4. Plot the standard histogram for valid ages
        plt.hist(valid_ages, bins=bins, edgecolor='black', label='Valid Ages')
        
        # 5. Plot the missing values as a distinct separate bar (e.g., at position 115)
        if nan_count > 0:
            # We place it slightly past the 100 mark so it doesn't overlap
            plt.bar(115, nan_count, width=8, color='orange', edgecolor='black', label='Missing Age')
            
            # Customizing the x-axis ticks to include our new "NaN" category
            tick_positions = list(bins) + [115]
            tick_labels = [str(b) for b in bins] + ['NaN']
            plt.xticks(tick_positions, tick_labels)
        else:
            plt.xticks(bins)
            
        # 6. Add labels and display
        plt.title('Age Distribution of Participants')
        plt.xlabel('Age')
        plt.ylabel('Frequency')
        plt.legend()
        plt.savefig('q1_age_distribution.png')
        plt.close()
        
        # Return only the standard hist and bins to pass the tests
        return hist, bin_edges

    # 2. Participants without a valid email are useless since we can't contact them. 
    # Remove all of the rows with an invalid address and return the new DataFrame. 
    # A valid email address is one that follows these conditions:
    #
    # * Contains exactly one "@" sign, but doesn't start or end with it.
    # * Contains a "." sign, but doesn't start or end with it.
    # * The letter following the "@" sign (i.e, appears after it) must not be ".".
    #
    # You're obviously encouraged to think of other email-defining conditions.

    def remove_rows_without_mail(self) -> pd.DataFrame:
        """Checks self.data for rows with invalid emails, and removes them.

        Returns
        -------
        df : pd.DataFrame
            A corrected DataFrame, i.e. the same table but with the erroneous rows removed and
            the (ordinal) index after a reset.
        """
        # Convert to string to easily handle NaN values
        email_series = self.data['email'].astype(str)

        # Keep addresses that have one @, a domain part, and a dot after the domain.
        # This accepts the sample data, including TLDs with one letter (e.g., ".c"), and rejects the invalid ones.
        pattern = r'^[^@\s]+@[^@\s]+\.[^@\s.]+$'
        valid_emails = email_series.str.contains(pattern, regex=True)

        # Apply the boolean mask directly to generate the new DataFrame
        return self.data[valid_emails].reset_index(drop=True)

    # 3. Some participants haven't answered all of the question. 
    # It was decided that the grade for those missing questions will be the average grade 
    # of the other question for that subject. 
    # Write a method that works on the original DataFrame (in self.data), 
    # replaces the missing values with the mean for that subject in the other questions and 
    # returns the corrected DataFrame as well as 
    # a np.array of the indices of the rows that were corrected.

    def fill_na_with_mean(self) -> Tuple[pd.DataFrame, np.ndarray]:
        """Finds, in the original DataFrame, the subjects that didn't answer
        all questions, and replaces that missing value with the mean of the
        other grades for that student.

        Returns
        -------
        df : pd.DataFrame
            The corrected DataFrame after insertion of the mean grade
        arr : np.ndarray
            Row indices of the students that their new grades were generated
        """
        # 1. Identify question columns
        question_cols = [col for col in self.data.columns if col.startswith('q')]

        # 2. Convert to numeric, forcing "nan" strings to np.nan
        self.data[question_cols] = self.data[question_cols].apply(pd.to_numeric, errors='coerce')

        # 3. Identify indices of rows with missing values
        mask = self.data[question_cols].isna().any(axis=1)
        arr = self.data[mask].index.to_numpy()

        # 4. Calculate the mean for each row (ignores NaNs by default)
        row_means = self.data[question_cols].mean(axis=1)

        # 5. Vectorized Fill: Apply the row_means to fill missing values column-by-column
        self.data[question_cols] = self.data[question_cols].apply(lambda col: col.fillna(row_means))

        return self.data, arr

    # 4. Each participants should receive an integer score for his or her answers, 
    # given in a new "score" column you should add. 
    # After some deliberation it was decided that if a subject has no grade in two questions or more, 
    # the score of that subject will be NA. 
    # Write a method that produces this score by averaging the grades of the not-NaN questions 
    # in the relevant rows.

    def score_subjects(self, maximal_nans_per_sub: int = 1) -> pd.DataFrame:
        """Calculates the average score of a subject and adds a new "score" column
        with it.

        If the subject has more than "maximal_nans_per_sub" NaN in his grades, the
        score should be NA. Otherwise, the score is simply the mean of the other grades.
        The datatype of score is UInt8, and the floating point raw numbers should be
        rounded down.

        Parameters
        ----------
        maximal_nans_per_sub : int, optional
            Number of allowed NaNs per subject before giving a NA score.

        Returns
        -------
        pd.DataFrame
            A new DF with a new column - "score".
        """
        # 1. Create a true copy so we don't mutate self.data
        df = self.data.copy()

        # 2. Identify question columns
        question_cols = [col for col in df.columns if col.startswith('q')]

        # 3. Coerce string "nan" to actual np.nan
        df[question_cols] = df[question_cols].apply(pd.to_numeric, errors='coerce')

        # 4. Count NaNs and calculate means per row
        nan_counts = df[question_cols].isna().sum(axis=1)
        mean_scores = df[question_cols].mean(axis=1)

        # 5. Round the raw floating point numbers down
        floored_scores = np.floor(mean_scores)

        # 6. Apply the NaN threshold
        final_scores = np.where(nan_counts > maximal_nans_per_sub, np.nan, floored_scores)

        # 7. Add the column, using Pandas' built-in ability to cast np.nan to pd.NA in UInt8 arrays
        df['score'] = pd.Series(final_scores, dtype='UInt8')

        return df

    # 5. BONUS 15 POINTS: There's reason to believe that there's a correlation 
    # between the subject's gender, age and grades.
    #
    # a. Use the original DataFrame and transform its index into a MultiIndex with three levels: 
    # the ordinal index (row number), gender and age.
    #
    # b. Allocate the different subjects into groups based on two parameters: 
    # Their gender, and whether their age is above or below 40. Hint - use `df.groupby`. 
    # The result should be similar to what is shown in the figure below 
    # in avg_per_group.png (you don't have to plot it yourself).
    #
    # c. Return the DataFrame containing the average result per question per group.

    def correlate_gender_age(self) -> pd.DataFrame:
        """Looks for a correlation between the gender of the subject, their age
        and the score for all five questions.

        Returns
        -------
        pd.DataFrame
            A DataFrame with a MultiIndex containing the gender and whether the subject is above
            40 years of age, and the average score in each of the five questions.
        """
        # 1. Create a true copy so we don't mutate self.data
        df = self.data.copy()

        # 2. Coerce string "nan" to actual np.nan for age and question columns
        df['age'] = pd.to_numeric(df['age'], errors='coerce')
        question_cols = [col for col in df.columns if col.startswith('q')]
        df[question_cols] = df[question_cols].apply(pd.to_numeric, errors='coerce')

        # 3. Drop rows with NaN in 'age' so they aren't incorrectly grouped as 'False' (<40)
        df = df.dropna(subset=['age'])

        # 4. Transform index into a 3-level MultiIndex (ordinal, gender, age)
        df.set_index(['gender', 'age'], append=True, inplace=True)

        # 5. Group by gender and whether age > 40
        # This automatically outputs a DataFrame with a MultiIndex!
        age_bool = df.index.get_level_values('age') > 40
        grouped = df.groupby([pd.Grouper(level='gender'), age_bool])[question_cols].mean()

        # Explicitly rename the levels to satisfy the test
        grouped.index.names = ['gender', 'age']

        # 6. Plotting the results
        # kind='bar' automatically creates clustered bars for each MultiIndex group
        grouped.plot(kind='bar', figsize=(10, 6), edgecolor='black')
        
        plt.title('Average Scores by Gender and Age Group (>40)')
        plt.xlabel('(Gender, Age > 40)')
        plt.ylabel('Average Score')
        
        # Move the legend outside the plot so it doesn't overlap the bars
        plt.legend(title='Questions', bbox_to_anchor=(1.05, 1), loc='upper left')
        plt.tight_layout()
        plt.savefig('q5_correlation_plot.png')
        plt.close()

        return grouped